default:
  image: registry.gitlab.com/mtczekajlo/rust-docker-images/x86_64-unknown-linux-gnu:00de5c9a24351e90eca251dc403abd2c3dff32e3ac42da95fb26772a1f9e2df4

stages:
  - check-and-build

check-and-build:
  stage: check-and-build
  script:
    - ci/check
    - ci/test
    - ci/build
