default:
  image: registry.gitlab.com/mtczekajlo/rust-docker-images/x86_64-unknown-linux-gnu:f16071885a5a3253b239d4308aa26c9d4a5c108ed6fd256367972a83f8e925a1

stages:
  - check-and-build

check-and-build:
  stage: check-and-build
  script:
    - ci/check
    - ci/test
    - ci/build
